### ISSUE TITLE
Avoid parenthesizing variables 

### ISSUE THREAD

**Issue by Icelandjack** [RyanGlScott/ghc#14]
Using `DerivingVia` in place of GND means we are forced to parenthesize

```haskell
newtype W a = W a deriving Show via (a)
```

make a special case for variables so GHC accepts

```haskell
newtype W a = W a deriving Show via a
```

**Comment by RyanGlScott** [comment]
Indeed. If you want to fix this, here are the relevant lines of code in the parser:

https://github.com/RyanGlScott/ghc/blob/04b246d279ea424086f70e08db490c0dc5ffbbc7/compiler/parser/Parser.y#L1121-L1127

Note that we currently lack a case for a bare type variable without parentheses. You should be able to steal that from this part of the parser:

https://github.com/RyanGlScott/ghc/blob/04b246d279ea424086f70e08db490c0dc5ffbbc7/compiler/parser/Parser.y#L1886

**Comment by Icelandjack** [comment]
Should not be required for lists either!

```haskell
newtype OrderedList a = OL [a] deriving Show via [a]
````

**Comment by RyanGlScott** [comment]
Yes, good point. The method by which I've been parsing types that come after `via` was adapted pretty much wholesale from the method by which GHC parses classes that come after `deriving`. Classes only have so many forms, so you can never have anything like `deriving [Foo]` or `deriving a`, which makes life a lot simpler.

But for `via` types, we really can put just about anything there. Well, except for things like `via Maybe Int`, since we want to make sure "compound" types like this are surrounded by parentheses. Adapting the parsing rules for classes that come after `deriving` does accomplish this, but as you've observed, it's far too conservative. We could add _ad hoc_ cases for bare type variables and lists, but surely some other case will pop up later that folks will complain about.

In light of this, I'd like to revise the advice I gave in https://github.com/RyanGlScott/ghc/issues/14#issuecomment-349669963. Instead of expanding the `deriv_strategy_via` parser production even further, I think we could simplify it down to just this:

```haskell
deriv_strategy_via :: { LDerivStrategy GhcPs } 
   : 'via' tyapp           {% ams (sLL $1 $> (ViaStrategy (mkLHsSigType $2))) 
                                  [mj AnnVia $1] }
```

I haven't tested this yet, but I think this would bring in exactly all of the types we need while excluding the compound ones. Care to give it a try, @Icelandjack?

**Comment by Icelandjack** [comment]
Ok trying this out

**Comment by Icelandjack** [comment]
It works using `btype` 

```haskell                                                                                                                                                                             
deriv_strategy_via :: { LDerivStrategy GhcPs }
  : 'via' btype                 {% ams (sLL $1 $> (ViaStrategy (mkLHsSigType $2)))
                                       [mj AnnVia $1] }
```

**Comment by RyanGlScott** [comment]
@Icelandjack has a WIP pull request for this at #17.

**Comment by Icelandjack** [comment]
I think 21a54d2 does what we want, the following is accepted now

```haskell
>> :set -XDerivingVia 
>> newtype I a = I a deriving Show via a
>> newtype I a = I [a] deriving Show via [a]
>> newtype I a = I (a, a) deriving Show via (a, a)
>> import Data.Monoid
>> newtype I a = I (Maybe a) deriving Show via (First a)
```

**Comment by RyanGlScott** [comment]
Excellent work. Can you add a test for this in `testsuite/tests/deriving/should_compile/deriving-via-compile.hs`?

**Comment by Icelandjack** [comment]
Added some tests in 0f9b095 and derived `MFunctor`.

**Comment by RyanGlScott** [comment]
Awesome! I'll go ahead and close this, then.
